services:
  app:
    build: .
    ports:
      - "8080:8080"
    working_dir: /workspaces
    env_file:
      - cmd/auction/.env
    volumes:
      - ./:/workspaces:cached
    command: sleep infinity
    networks:
      - localNetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork

volumes:
  mongo-data:
    driver: local

networks:
  localNetwork:
    driver: bridge
