services:
  app:
    image: golang:1.20
    ports:
      - "8080:8080"
    env_file:
      - ../cmd/auction/.env
    volumes:
      - ../:/workspaces:cached
    command: sleep infinity
    networks:
      - localNetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - ../cmd/auction/.env
    networks:
      - localNetwork

networks:
  localNetwork:
    driver: bridge
